[project]
name = "scholarly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai>=0.141.0",
    "openai>=1.95.1",
    "tiktoken>=0.9.0",
    "tts",
]
