topic: "{paper_topic}"
agents:
  - paper_ingestor
  - summarizer
  - narrator
  - qna_analyst
  - metadata_agent
  - controller

tasks:
  - id: extract_paper
    description: >
      Extract text from the research paper "{paper_name}" and identify the title, abstract, introduction, and conclusion.
    agent: paper_ingestor
    context: []
    expected_output: >
      Structured sections of the paper including title, abstract, introduction, and conclusion.

  - id: summarize_sections
    description: >
      Summarize the following extracted sections from the paper "{inputs.paper_name}": 

      {inputs.full_text}
    agent: summarizer
    context: []
    expected_output: >
      A clean summary of abstract, introduction, and conclusion.

  - id: narrate_summary
    description: >
      Convert the summarized content of "{paper_name}" into clear, engaging speech using a natural-sounding voice.
    agent: narrator
    depends_on: [summarize_sections]
    context: []
    expected_output: >
      An audio file (e.g., MP3 or WAV) containing the narrated summary.

  - id: extract_metadata
    description: >
      Retrieve and display metadata for the paper "{paper_name}" including authors, publication date, and affiliations.
    agent: metadata_agent
    depends_on: [extract_paper]
    context: []
    expected_output: >
      Structured metadata for user reference.

  - id: answer_questions
    description: >
      Answer user-generated questions about the paper "{paper_name}" using the extracted and summarized content.
    agent: qna_analyst
    depends_on: [summarize_sections]
    context: []
    expected_output: >
      A list of user questions and accurate answers based on the paper.

  - id: coordinate_workflow
    description: >
      Oversee and manage the workflow for processing the paper "{paper_name}", ensuring all agents complete their work in order.
    agent: controller
    depends_on: [extract_paper, summarize_sections, narrate_summary, extract_metadata, answer_questions]
    context: []
    expected_output: >
      A status report confirming successful execution of the pipeline for "{paper_name}".
